# Generated by Django 4.2.2 on 2023-07-31 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_alter_comment_user_alter_goalcategory_board'),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='goal_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goals.goalcategory', verbose_name='выбранная категория'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='state',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Waiting for Category'), (2, 'Waiting for Goal Name')], default=0, verbose_name='состояние пользователя'),
        ),
    ]
